// <auto-generated />
using System;
using Catalog.Infrastructure.Persistence.Configurations;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Catalog.Infrastructure.Migrations
{
    [DbContext(typeof(CatalogDbContext))]
    partial class CatalogDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Catalog.Domain.Entities.ArticuloEtiqueta", b =>
                {
                    b.Property<Guid>("ArticuloId")
                        .HasColumnType("uuid");

                    b.Property<int>("EtiquetaId")
                        .HasColumnType("integer");

                    b.HasKey("ArticuloId", "EtiquetaId");

                    b.HasIndex("EtiquetaId");

                    b.ToTable("ArticuloEtiqueta", "catalog");
                });

            modelBuilder.Entity("Catalog.Domain.Entities.ArticuloPublicado", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ArchivoUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Carrera")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaPublicacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Materia")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NombresAutores")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Resumen")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("RevisionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ArticulosPublicados", "catalog");
                });

            modelBuilder.Entity("Catalog.Domain.Entities.Etiqueta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Etiquetas", "catalog");
                });

            modelBuilder.Entity("Catalog.Domain.Entities.ArticuloEtiqueta", b =>
                {
                    b.HasOne("Catalog.Domain.Entities.ArticuloPublicado", "Articulo")
                        .WithMany("ArticuloEtiquetas")
                        .HasForeignKey("ArticuloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Catalog.Domain.Entities.Etiqueta", "Etiqueta")
                        .WithMany("ArticuloEtiquetas")
                        .HasForeignKey("EtiquetaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Articulo");

                    b.Navigation("Etiqueta");
                });

            modelBuilder.Entity("Catalog.Domain.Entities.ArticuloPublicado", b =>
                {
                    b.Navigation("ArticuloEtiquetas");
                });

            modelBuilder.Entity("Catalog.Domain.Entities.Etiqueta", b =>
                {
                    b.Navigation("ArticuloEtiquetas");
                });
#pragma warning restore 612, 618
        }
    }
}
