version: '3.8'

services:
  db_biblioteca:
    image: postgres:15-alpine # Versión ligera y estable
    container_name: ucb_postgres_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER} # Usuario local de desarrollo
      POSTGRES_PASSWORD: ${DB_PASSWORD} # Contraseña local de desarrollo
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432" # Mapea el puerto del contenedor a la computadora
    volumes:
      - pgdata:/var/lib/postgresql/data # Hace que los datos no se borren si se apaga el contenedor

volumes:
  pgdata: